# Generated by Django 4.1.7 on 2023-04-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_analista', models.CharField(default='', max_length=50, verbose_name='Nome Profissional')),
                ('nm_medico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Médico')),
                ('nm_hospital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Hospital')),
                ('tel_contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone Contato')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('dt_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do atendimento')),
                ('servico_analisado', models.TextField(blank=True, null=True, verbose_name='Tipo de validação')),
                ('upload', models.FileField(blank=True, null=True, upload_to='dados/')),
                ('utiliza_protocolo', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')], null=True, verbose_name='Utiliza protocolo gerenciavel ?')),
                ('utiliza_rotina_especial', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')], null=True, verbose_name='Utiliza rotina especial ?')),
                ('utiliza_rotina', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')], null=True, verbose_name='Utiliza rotina ?')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_medico', models.CharField(blank=True, max_length=200, null=True)),
                ('crm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cod Conselho')),
            ],
        ),
    ]
