# Generated by Django 4.1.7 on 2023-04-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat_s', '0002_alter_medico_crm_alter_medico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cod Conselho'),
        ),
    ]
