# Generated by Django 4.1.7 on 2023-04-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rat_s', '0003_alter_medico_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='nm_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rat_s.medico', verbose_name='Nome Medico'),
        ),
    ]
