# Generated by Django 4.1.7 on 2023-03-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_analista', models.CharField(default='', max_length=50, verbose_name='Nome Profissional')),
                ('nm_medico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Médico')),
                ('nm_hospital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Hospital')),
                ('tel_contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone Contato')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('dt_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do atendimento')),
                ('servico_analisado', models.TextField(blank=True, null=True, verbose_name='Tipo de validação')),
                ('utiliza_protocolo', models.BooleanField(default=False, verbose_name='Utiliza protocolo gerenciavel ?')),
                ('utiliza_rotina_especial', models.BooleanField(default=False, verbose_name='Utiliza rotina especial ?')),
                ('utiliza_rotina', models.BooleanField(default=False, verbose_name='Utiliza rotina ?')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('upload', models.ImageField(blank=True, null=True, upload_to='dados/')),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
