# Generated by Django 4.1.7 on 2023-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat_s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
